# https://github.com/oracle-devrel/action-license-audit/blob/main/.github/workflows/repolinter.yml

name: Repolinter
on:
  pull_request_target:

permissions: write-all

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run_repolinter:
    name: Run Repolinter on pull request
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/oracledevrel/repolinter:v0.11.1
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # or your preferred version
          bundler-cache: true # runs 'bundle install' for you
      - name: Run Repolinter
        run: |
          set +e
          bundle exec /app/bin/repolinter.js lint --format json --rulesetFile repolinter.json . > repolinter_results.json
          echo "\n\nHere is the repolinter_results.json:\n"
          echo $(cat repolinter_results.json)
          exit 0

      - name: print env variable
        run: |
          env

      - name: get github token
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
        
